name: lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  golangci-lint:
    name: lint library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
      # Keep version in sync with the golangci-lint tool dependency in go.mod.
      - uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1
        with:
          version: v2.11.4
